format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$fill\
$all\    
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

right_format = """
$time\
"""

[fill]
symbol = " . "

[character]
vicmd_symbol = "[](bold green)"

# [time]
# disabled = false
# format = '[ $time]($style)'
# time_range = "22:00:00-06:00:00"

[package]
symbol = " "

[rust]
symbol = " "

[python]
symbol = " "

[nodejs]
symbol = " "

[java]
symbol = " "

[dart]
symbol = " "

[golang]
symbol = " "

[docker_context]
symbol = " "

[sudo]
symbol = " "
disabled = false
