"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$fill\
$all\
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

right_format = """
$time\
"""

[fill]
symbol = " . "
style = "bold white"

[character]
vimcmd_symbol = "[](bold cyan)"
vimcmd_replace_one_symbol = "[](bold purple)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_visual_symbol = "[](bold yellow)"

# [time]
# disabled = false
# format = '[ $time]($style)'
# time_range = "22:00:00-06:00:00"

[package]
symbol = "󰏗 "

[rust]
symbol = " "

[python]
symbol = " "

[nodejs]
symbol = " "

[java]
symbol = " "

[dart]
symbol = " "

[golang]
symbol = " "

[docker_context]
symbol = " "

[sudo]
symbol = " "
disabled = false

[custom.amplify]
detect_folders = ["amplify"]
command = "jq -cr '.envName' amplify/.config/local-env-info.json"
style = "purple"
symbol = "󰸏"
format = """[$symbol $output]($style) """
