local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>ha", mark.add_file, { desc = "Harpoon add file" })
vim.keymap.set("n", "<leader>hu", ui.toggle_quick_menu, { desc = "Harpoon quick menu" })
vim.keymap.set("n", "<leader>hn", function()
    ui.nav_file(1)
end, { desc = "Harpoon nav 1" })
vim.keymap.set("n", "<leader>he", function()
    ui.nav_file(2)
end, { desc = "Harpoon nav 2" })
vim.keymap.set("n", "<leader>hi", function()
    ui.nav_file(3)
end, { desc = "Harpoon nav 3" })
vim.keymap.set("n", "<leader>ho", function()
    ui.nav_file(4)
end, { desc = "Harpoon nav 4" })
