require("telescope").setup({})
pcall(require("telescope").load_extension, "fzf")

local telescope = require("telescope.builtin")

vim.keymap.set("n", "<leader>sb", telescope.buffers, { desc = "Search buffers" })
vim.keymap.set("n", "<leader>sc", telescope.grep_string, { desc = "Search current word" })
vim.keymap.set("n", "<leader>sd", telescope.diagnostics, { desc = "Search diagnostics" })
vim.keymap.set("n", "<leader>sd", telescope.diagnostics, { desc = "Search diagnostics" })
vim.keymap.set("n", "<leader>sf", telescope.find_files, { desc = "Search files" })
vim.keymap.set("n", "<leader>sh", telescope.help_tags, { desc = "Search help" })
vim.keymap.set("n", "<leader>sk", telescope.keymaps, { desc = "Search keymaps" })
vim.keymap.set("n", "<leader>so", telescope.oldfiles, { desc = "Search oldfiles" })
vim.keymap.set("n", "<leader>sw", telescope.live_grep, { desc = "Search by grep" })
vim.keymap.set("n", "<leader>sg", telescope.git_files, { desc = "Search Git Files" })
